services:
  # ==================================================
  java-box:
    container_name: "java-box"
    build:
      context: ./java-box
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC_PARTITIONS: ${KAFKA_TOPIC_PARTITIONS}
      KAFKA_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
    networks:
      - shared-network

  blog-server:
    container_name: "blog-service"
    build:
      context: ./blog-service
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    networks:
      - shared-network


  notification-server:
    container_name: "notification-service"
    build:
      context: ./notification-service
    depends_on:
      - blog-server
      - rabbitmq
    ports:
      - "8082:8082"
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    networks:
      - shared-network

  # ==================================================

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-network

  # ==================================================

  kafka-1:
    image: confluentinc/cp-kafka:7.8.0
    hostname: ${KAFKA1_NAME}
    container_name: ${KAFKA1_NAME}
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA1_NAME}:9093,2@${KAFKA2_NAME}:9093,3@${KAFKA3_NAME}:9093
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA1_NAME}:9092,CONTROLLER://${KAFKA1_NAME}:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA1_NAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${CLUSTER_ID}
    volumes:
      - kafka1-data:/var/lib/kafka/data
    networks:
      - shared-network

  kafka-2:
    image: confluentinc/cp-kafka:7.8.0
    hostname: ${KAFKA2_NAME}
    container_name: ${KAFKA2_NAME}
    ports:
      - "9094:9092"
      - "9095:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA1_NAME}:9093,2@${KAFKA2_NAME}:9093,3@${KAFKA3_NAME}:9093
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA2_NAME}:9092,CONTROLLER://${KAFKA2_NAME}:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA2_NAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${CLUSTER_ID}
    volumes:
      - kafka2-data:/var/lib/kafka/data
    networks:
      - shared-network

  kafka-3:
    image: confluentinc/cp-kafka:7.8.0
    hostname: ${KAFKA3_NAME}
    container_name: ${KAFKA3_NAME}
    ports:
      - "9096:9092"
      - "9097:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA1_NAME}:9093,2@${KAFKA2_NAME}:9093,3@${KAFKA3_NAME}:9093
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA3_NAME}:9092,CONTROLLER://${KAFKA3_NAME}:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA3_NAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: ${CLUSTER_ID}
    volumes:
      - kafka3-data:/var/lib/kafka/data
    networks:
      - shared-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8181:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_UI_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA1_NAME}:9092,${KAFKA2_NAME}:9092,${KAFKA3_NAME}:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - shared-network

  # ==================================================

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8180:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}

  # ==================================================

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  mongo-data:
    driver: local

networks:
  shared-network:
    driver: bridge
