services:
  # ==================================================
  blog-server:
    container_name: "blog-service"
    build:
      context: ./blog-service
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    networks:
      - shared-network


  notification-server:
    container_name: "notification-service"
    build:
      context: ./notification-service
    depends_on:
      - blog-server
      - rabbitmq
    ports:
      - "8082:8082"
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    networks:
      - shared-network

  # ==================================================

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-network

  # ==================================================

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}

  # ==================================================

volumes:
  mongo-data:
    driver: local

networks:
  shared-network:
    driver: bridge
